DROP TABLESPACE tem_team_2222
	INCLUDING CONTENTS
    CASCADE CONSTRAINTS;
	
DROP TABLESPACE temm_team_2222
	INCLUDING CONTENTS
    CASCADE CONSTRAINTS;
	
DROP TABLESPACE def_team_2222
	INCLUDING CONTENTS
    CASCADE CONSTRAINTS;
	
DROP TABLESPACE tbs_team_2222
	INCLUDING CONTENTS
    CASCADE CONSTRAINTS;